version: "3.9"
services:
  web:
    build: ./web/
    container_name: web_container
    ports: 
      - "8080:80"
    networks:
      hillel:
        ipv4_address: 192.168.0.10

  mysql:
    build: ./mysql/
    container_name: mysql_container
    restart: always
    networks:
      hillel:
        ipv4_address: 192.168.0.20
    volumes:
      - ./db_data:/var/lib/mysql

networks:
  hillel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  
volumes:
  db_data:
    external: true